/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        /* ── SPECTRA 4.1 Design System — exact tokens from original screens ── */
        'primary':                  '#00288e',
        'on-primary':               '#ffffff',
        'primary-container':        '#1e40af',
        'on-primary-container':     '#a8b8ff',
        'primary-fixed':            '#dde1ff',
        'primary-fixed-dim':        '#b8c4ff',
        'on-primary-fixed':         '#001453',
        'on-primary-fixed-variant': '#173bab',
        'inverse-primary':          '#b8c4ff',
        'secondary':                '#006a61',
        'on-secondary':             '#ffffff',
        'secondary-container':      '#86f2e4',
        'on-secondary-container':   '#006f66',
        'secondary-fixed':          '#89f5e7',
        'secondary-fixed-dim':      '#6bd8cb',
        'on-secondary-fixed':       '#00201d',
        'on-secondary-fixed-variant':'#005049',
        'tertiary':                 '#273548',
        'on-tertiary':              '#ffffff',
        'tertiary-container':       '#3e4c60',
        'on-tertiary-container':    '#aebcd4',
        'tertiary-fixed':           '#d5e3fc',
        'tertiary-fixed-dim':       '#b9c7df',
        'on-tertiary-fixed':        '#0d1c2e',
        'on-tertiary-fixed-variant':'#3a485b',
        'error':                    '#ba1a1a',
        'on-error':                 '#ffffff',
        'error-container':          '#ffdad6',
        'on-error-container':       '#93000a',
        'surface':                  '#f9f9ff',
        'surface-dim':              '#d3daef',
        'surface-bright':           '#f9f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low':    '#f1f3ff',
        'surface-container':        '#e9edff',
        'surface-container-high':   '#e1e8fd',
        'surface-container-highest':'#dce2f7',
        'surface-variant':          '#dce2f7',
        'on-surface':               '#141b2b',
        'on-surface-variant':       '#444653',
        'inverse-surface':          '#293040',
        'inverse-on-surface':       '#edf0ff',
        'surface-tint':             '#3755c3',
        'background':               '#f9f9ff',
        'on-background':            '#141b2b',
        'outline':                  '#757684',
        'outline-variant':          '#c4c5d5',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg:      '0.25rem',
        xl:      '0.5rem',
        full:    '0.75rem',
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '0.75rem',
        'space-lg': '1rem',
        'space-xl': '1.5rem',
        'margin':   '0.5rem',
        'gutter':   '0.5rem',
      },
      fontFamily: {
        'body-md':      ['Inter', 'sans-serif'],
        'body-sm':      ['Inter', 'sans-serif'],
        'body-lg':      ['Inter', 'sans-serif'],
        'headline-sm':  ['Inter', 'sans-serif'],
        'headline-md':  ['Inter', 'sans-serif'],
        'headline-lg':  ['Inter', 'sans-serif'],
        'label-sm':     ['"JetBrains Mono"', 'monospace'],
        'label-md':     ['"JetBrains Mono"', 'monospace'],
        'label-lg':     ['"JetBrains Mono"', 'monospace'],
        'metric-display': ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'body-md':       ['0.8125rem', { lineHeight: '1.125rem', letterSpacing: '0em',     fontWeight: '400' }],
        'body-sm':       ['0.75rem',   { lineHeight: '1rem',     letterSpacing: '0em',     fontWeight: '400' }],
        'body-lg':       ['0.875rem',  { lineHeight: '1.25rem',  letterSpacing: '0em',     fontWeight: '400' }],
        'headline-sm':   ['0.875rem',  { lineHeight: '1.125rem', letterSpacing: '0em',     fontWeight: '600' }],
        'headline-md':   ['1rem',      { lineHeight: '1.25rem',  letterSpacing: '-0.005em',fontWeight: '600' }],
        'headline-lg':   ['1.25rem',   { lineHeight: '1.5rem',   letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-sm':      ['0.6875rem', { lineHeight: '0.75rem',  letterSpacing: '0em',     fontWeight: '400' }],
        'label-md':      ['0.75rem',   { lineHeight: '0.875rem', letterSpacing: '-0.01em', fontWeight: '500' }],
        'label-lg':      ['0.8125rem', { lineHeight: '1rem',     letterSpacing: '-0.02em', fontWeight: '500' }],
        'metric-display':['1.5rem',    { lineHeight: '1.75rem',  letterSpacing: '-0.03em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};
